orbisoperations/catalyst

apps/organization_matchmaking/README.md

Added a new Organization Matchmaking service for managing partnerships between organizations in the Catalyst platform.
Created a README.md file for the Organization Matchmaking service that outlines:
- The purpose of the service for facilitating organization-to-organization collaborations
- The architecture using Cloudflare Workers and Durable Objects
- Core features including invitation management (send, accept, decline, list, read)
- Partnership management capabilities (toggle, status tracking, custom messages)
- Security controls with permission-based access
Review the README.md documentation to understand the service's capabilities and architecture. The actual implementation can be tested once the service is deployed by:
1. Creating partnership invitations between organizations
2. …

add readme to org matchmaking

---

apps/data_channel_registrar/README.md

Added a README for the Data Channel Registrar service, documenting its purpose, architecture, and features.
Created a new README.md file for the Data Channel Registrar application that:
- Explains the service's purpose as a central registry for tracking data channels and managing access permissions
- Details the architecture using Cloudflare Workers, Durable Objects, and TypeScript
- Documents key features including data channel management operations (CRUD)
- Describes permission management capabilities including organization isolation and JWT-based access
- Outlines how the service integrates with the broader Catalyst ecosystem
Review the README.md file in the apps/data_channel_registrar directory to ensure it accurately describes the service's functionality and provides sufficient …

add readme to data channel registrar

---

apps/data_channel_gateway/README.md

Enhanced the Data Channel Gateway README with comprehensive documentation about the service's purpose, architecture, and features.
Expanded the README.md file for the Data Channel Gateway service with:
- Added a clear service description and purpose statement
- Documented the architecture and technology stack (Cloudflare Workers, Hono, GraphQL Yoga, etc.)
- Outlined key features including GraphQL federation and dynamic schema stitching
- Added integration details with other services like Data Channel Registrar, AuthX, and User Credentials Cache
- Updated the development and deployment commands to use pnpm instead of npm
Review the README.md file to ensure it provides clear and comprehensive information about the Data Channel Gateway service.
This documentation improvement helps developers …

init README data channel gateway

---

apps/authx_authzed_api/README.md

Added README.md for the AuthX AuthZed API service.
Created a new README.md file for the AuthX AuthZed API service that provides documentation about this Cloudflare Workers-based authorization system. The README includes sections on:
- Purpose of the service as an authorization layer for Catalyst
- Architecture details (Cloudflare Workers, AuthZed, TypeScript)
- Main components (AuthzedWorker, AuthzedClient, AuthzedUtils)
- Integration with other Catalyst services
Review the README.md content to ensure it accurately describes the AuthX AuthZed API service and its role within the Catalyst ecosystem.
To provide documentation for the AuthX AuthZed API service, making it easier for developers to understand its purpose, architecture, and integration points with other services in the Catalyst …

Add AuthX AuthZed API documentation

---

apps/authx_authzed_api/wrangler.toml

before change:
```
ihammerstrom@Ians-MacBook-Pro apps % cd authx_authzed_api && pnpm wrangler dev --port 5054
⛅️ wrangler 4.9.1
------------------
✘ [ERROR] Processing wrangler.toml configuration:
- Removed: "node_compat":
The "node_compat" field is no longer supported
as of Wrangler v4. Instead, use the `nodejs_compat`
compatibility flag. This includes the functionality
from legacy `node_compat` polyfills and natively
implemented Node.js APIs. See
https://developers.cloudflare.com/workers/runtime-apis/nodejs
for more information.
```
after change:
```
hammerstrom@Ians-MacBook-Pro authx_authzed_api % pnpm wrangler dev --port 5054
⛅️ wrangler 4.9.1
------------------
No bindings found.
⎔ Starting local server...
[wrangler:inf] Ready on http://localhost:5054 …
```

fix(authx_authzed_api): replace deprecated node_compat with nodejs_compat for Wrangler v4

---

apps/authx_token_api/package.json
apps/data_channel_gateway/package.json
apps/data_channel_registrar/package.json
apps/issued-jwt-registry/package.json
examples/datachannel_airplanes/package.json
examples/datachannel_cars/package.json
examples/datachannel_manufactures/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Assigned specific ports to Wrangler dev servers and standardized pnpm usage across examples.
- Assigned dedicated ports to Wrangler dev servers:
- `authx_token_api`: port 5052
- `data_channel_gateway`: port 5051
- `data_channel_registrar`: port 5050
- `issued-jwt-registry`: port 5053
- Added `start` scripts to services that were missing them
- Standardized the use of `pnpm` instead of `npx` in example projects
- Added `kill-port` as a dependency to the catalog and example projects
1. Run the dev servers for different services simultaneously using:
```
pnpm dev
```
2. Verify each service starts on its designated port
3. Test that the `start` scripts work correctly for services where they were added
This change prevents port conflicts when running multiple services simultaneously during …

setup development ports on pacakge.json dev command instead of wrangler.jsonc

---

apps/user_credentials_cache/src/index.ts
apps/user_credentials_cache/test/index.spec.ts

Export the `getOrgFromRoles` function and add comprehensive test coverage for the user credentials cache.
- Made `getOrgFromRoles` function exportable by adding the `export` keyword
- Added extensive test coverage for the `UserCredsCache` module:
- Tests for `getOrgFromRoles` function to verify it correctly extracts organization and roles
- Tests for retrieving users from cache when they exist
- Tests for validating and caching users on cache miss
- Tests for handling validation failures
- Tests for the `purge` function to ensure it properly removes old tokens for the same user
1. Run the test suite for the user credentials cache:
```
npm test -- apps/user_credentials_cache
```
2. Verify all tests pass, including the new tests for `getOrgFromRoles`, cache retrieval, validation, and …

Export getOrgFromRoles function and add comprehensive tests

---

apps/authx_authzed_api/package.json
apps/authx_token_api/package.json
apps/catalyst-ui-worker/package.json
apps/data_channel_gateway/package.json
apps/data_channel_registrar/package.json
apps/issued-jwt-registry/package.json
run_local_dev.sh

Standardized development ports across all services and improved the local development script.
- Updated development ports for all services to avoid conflicts:
- `authx_authzed_api`: Set port to 5050
- `authx_token_api`: Changed port from 5052 to 5051
- `catalyst-ui-worker`: Added port 4000 to preview command
- `data_channel_gateway`: Changed port from 5051 to 5053
- `data_channel_registrar`: Changed port from 5050 to 5054
- `issued-jwt-registry`: Changed port from 5053 to 5055
- Removed redundant `start` scripts from package.json files
- Enhanced `run_local_dev.sh` script:
- Improved PID tracking and process management
- Added better error handling for the authzed container
- Fixed the catalyst-ui-worker command detection
1. Run the updated `run_local_dev.sh` script
2. Verify all services …

updated ports for pnpm dev

---

apps/TESTING.md
apps/authx_authzed_api/README.md
apps/authx_authzed_api/src/authzed.ts
apps/data_channel_gateway/tests/authzed.spec.ts
apps/data_channel_gateway/tests/schema-resilience.spec.ts
apps/data_channel_registrar/README.md
apps/data_channel_registrar/src/worker.ts
apps/data_channel_registrar/test/index.spec.ts
apps/data_channel_registrar/test/integration.spec.ts
apps/data_channel_registrar/vitest.config.ts
apps/user-credentials-cache/src/index.ts
apps/user-credentials-cache/test/index.spec.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Enhanced testing documentation with detailed guides for permission system integration testing and improved SpiceDB development workflows.
- Added comprehensive documentation for integration testing with the SpiceDB permission system
- Expanded the TESTING.md guide with examples for setting up permission relationships and testing resource access
- Enhanced the authx_authzed_api README with detailed instructions for using the ZED CLI tool
- Improved documentation for local development with SpiceDB, including container setup and CLI usage
- Added examples for testing with preconfigured users and permission relationships
- Fixed and improved integration tests in data_channel_registrar
- Updated the vitest configuration with proper user mocking for Cloudflare Access
1. Review the updated …

chore(docs & testing): updated documentation for authzed development and testing for data channel registrar

---

apps/TESTING.md
apps/data_channel_gateway/README.md
apps/data_channel_gateway/tests/authzed.spec.ts
apps/data_channel_gateway/tests/index.spec.ts
apps/data_channel_gateway/vitest.config.ts

Tests passing, were failing before. Details and test output below:
1. **Authzed Service Binding Configuration**
- Added `serviceBindings` configuration in `vitest.config.ts` to properly bind the `AUTHZED` service to `authx_authzed_api`
2. **Test Improvements in `authzed.spec.ts`**
- Enhanced the "add, list, and delete data channels" test with proper cleanup
- Added pre-test cleanup to remove existing data channels
- Improved error handling and logging
- Added more detailed console logging for debugging
3. **Test Refactoring in `index.spec.ts`**
- Introduced proper TypeScript interfaces for `DataChannel` and `ExtendedProvidedEnv`
- Refactored setup and teardown functions to be more focused and maintainable
- Improved the "should get datachannel for airplanes" test:
- Added proper …

fix: update authzed service binding configuration and test setup

---

.husky/pre-commit
.prettierrc
apps/authx_authzed_api/package.json
apps/authx_token_api/global-setup.ts
apps/authx_token_api/package.json
apps/data_channel_gateway/package.json
apps/data_channel_gateway/tests/index.spec.ts
apps/data_channel_registrar/package.json
apps/issued-jwt-registry/package.json
apps/organization_matchmaking/package.json
apps/user-credentials-cache/package.json
eslint.config.mjs
package.json
packages/schema_zod/tsconfig.json
pnpm-lock.yaml

- Added a silent test mode for workspace testing and updated code formatting configuration. 
- `test:workspace` script to all `/package.json` files that runs all supported apps.
- new test dependency in `global-setup.ts` for vitest-testing of `apps/auth_token_api`
- Updated the root `package.json` to use the new silent test mode for workspace testing
- Modified Prettier configuration to include `printWidth: 120` and `proseWrap: "preserve"`
- Changed `semicolon` setting from `false` to `true` in Prettier config
- Added `issued-jwt-registry` to the dependencies list in global-setup.ts
- Fixed code formatting on files on this commit
- Fixed a TODO comment in data_channel_gateway tests
1. Run `pnpm test`  on `<rootDir>` to verify the silent test mode works across all packages
2. Check that …

chore(test): project wide testing implemented for supported apps

---

README.md
apps/catalyst-ui-worker/wrangler.jsonc
run_local_dev.sh

Added a `--no-ui` flag to the local development script to allow running the backend services without the UI worker.
- Added command line argument parsing to `run_local_dev.sh`
- Implemented a `--no-ui` flag that, when specified, excludes the UI worker from the startup process
- Moved the UI worker from being commented out in the app order list to being conditionally added based on the flag
- Added usage information that displays when invalid arguments are provided
1. Run the script normally to start all services including the UI:
```
./run_local_dev.sh
```
2. Run the script with the new flag to start only backend services:
```
./run_local_dev.sh --no-ui
```
3. Verify that when using `--no-ui`, the catalyst-ui-worker service does not start
This change provides developers with more …

feat: add no ui option to startup script

---

.husky/pre-commit
apps/organization_matchmaking/package.json
apps/organization_matchmaking/vitest.config.ts
pnpm-lock.yaml

Added test coverage configuration for the organization matchmaking app.
- Updated package dependencies in organization_matchmaking to use specific versions instead of catalog references
- Added a new `test:coverage` script to the organization_matchmaking package.json
- Added Istanbul coverage configuration to vitest.config.ts with appropriate exclusion patterns
- Removed deployment scripts for demo and staging environments
1. Run `pnpm test:coverage` in the organization_matchmaking directory to verify coverage reporting works
2. Make a commit to verify that tests now run as part of the pre-commit hook
3. Check that the coverage reports are generated in HTML, JSON, and text formats
This change improves the development workflow by ensuring tests run before each commit, preventing broken …

test(organization-matchmaking): add coverage

---

apps/issued-jwt-registry/package.json
apps/issued-jwt-registry/vitest.config.ts
pnpm-lock.yaml

Updated the issued-jwt-registry app with explicit dependency versions and added code coverage configuration.
- Replaced catalog references with explicit version numbers for all dependencies in package.json
- Added a new `test:coverage` script to package.json
- Added the `@vitest/coverage-istanbul` dependency for code coverage reporting
- Updated the Vitest configuration to use `defineWorkersConfig` instead of `defineWorkersProject`
- Configured comprehensive code coverage settings with Istanbul provider
- Added coverage reporters (text, HTML, JSON summary, and LCOV)
- Defined specific include/exclude patterns for coverage reporting
1. Run `pnpm install` to update dependencies
2. Execute `pnpm test:coverage` in the issued-jwt-registry directory
3. Verify that coverage reports are generated …

test(issued-jwt-registry): add coverage

---

apps/authx_authzed_api/package.json
apps/authx_authzed_api/vitest.config.ts
apps/authx_token_api/package.json
apps/authx_token_api/vitest.config.ts
pnpm-lock.yaml

Added code coverage configuration and updated package dependencies to use explicit versions instead of catalog references.
- Added test coverage configuration with Istanbul provider to both `authx_authzed_api` and `authx_token_api` projects
- Added `test:coverage` script to both projects' package.json files
- Updated all dependencies to use explicit version numbers instead of `catalog:` references
- Removed deployment scripts from `authx_authzed_api`
- Fixed code formatting in the `validUsers` object in `authx_token_api/vitest.config.ts`
1. Run `pnpm test:coverage` in either project directory to generate coverage reports
2. Verify that coverage reports are generated in the `./coverage` directory
3. Check that the HTML, text, and JSON summary reports are available
This change improves the …

test(authx): add istanbul coverage to authx_authzed_api and authx_token_api

---

apps/organization_matchmaking/src/index.ts
apps/organization_matchmaking/test/index.spec.ts
apps/organization_matchmaking/vitest.config.ts

Fixed organization partnership toggle functionality to update both sender and receiver mailboxes, ensuring consistent state across organizations.
- Enhanced the `togglePartnership` method to update the invite status in both the sender and receiver mailboxes
- Added validation to check if the invite exists in both mailboxes before toggling
- Fixed the response object in the `respond` method to include the status field
- Improved test coverage with comprehensive tests for invite management functionality
- Added type guards and standardized mock user creation for better type safety
1. Create an invite between two organizations
2. Toggle the partnership status using the `togglePartnership` endpoint
3. Verify that the invite status is updated in both the sender and receiver mailboxes
4. Try …

feat: added unit testing for org matchmaking

---

apps/authx_token_api/global-setup.ts
apps/authx_token_api/src/durable_object_security_module.ts
apps/authx_token_api/src/env.d.ts
apps/authx_token_api/src/index.ts
apps/authx_token_api/vitest.config.ts
apps/authx_token_api/wrangler.jsonc
apps/data_channel_gateway/src/env.d.ts
apps/data_channel_gateway/src/index.ts
apps/data_channel_gateway/src/tokenGenerators.ts
apps/data_channel_gateway/src/types.ts
apps/data_channel_gateway/tests/index.spec.ts
apps/data_channel_gateway/tests/jwt-registry.spec.ts
apps/data_channel_gateway/vitest.config.ts
apps/data_channel_gateway/wrangler.jsonc
apps/data_channel_registrar/src/worker.ts
apps/data_channel_registrar/vitest.config.ts
run_local_dev.sh

Added single-use JWT functionality to the token API for data channel access, improving security by generating short-lived tokens for each data channel request.
- Added a new `decodeToken` method to the JWT Key Provider to extract payload information
- Implemented `signSingleUseJWT` function in the token API to create short-lived tokens for data channels
- Updated the data channel gateway to use single-use tokens instead of passing the main Catalyst token
- Added the data channel registrar as a dependency to the token API
- Created new helper files in the data channel gateway for token generation
- Fixed type definitions and improved error handling throughout the codebase
1. no unit tests implemented yet. Incomming in next PR
This change improves security by implementing the principle of …

feat(secure-token): added initial valid implementation for secure exchange of ctTokens to producers

---

apps/data_channel_gateway/src/index.ts
apps/data_channel_gateway/tests/index.spec.ts
apps/data_channel_gateway/tests/testUtils.ts
packages/jwt/tsconfig.json

Added tests for single-use token generation in the data channel gateway.
- Added tests to verify single-use token generation functionality with both single and multiple claims
- Added a test to verify behavior when attempting to create a single-use token with an undefined catalyst token
- Created a utility function `isWithinRange` to check if a timestamp falls within an expected range
- Added a TypeScript ignore comment to handle a type mismatch with status codes
- Updated test setup and teardown to properly clean up test resources
- Added before/after hooks to run setup and teardown for each test
1. Run the test suite for the data channel gateway:
```
cd apps/data_channel_gateway
npm test
```
2. Verify that all tests pass, including the new single-use token tests
This change improves …

feat(secure-token): added unit testing for CT Token with single and multiple claims

---

apps/data_channel_registrar/package.json
apps/data_channel_registrar/src/env.d.ts
apps/data_channel_registrar/src/worker.ts
apps/data_channel_registrar/test/env.d.ts
apps/data_channel_registrar/test/index.spec.ts
apps/data_channel_registrar/test/integration.spec.ts
apps/data_channel_registrar/test/testUtils.ts
apps/data_channel_registrar/vitest.config.ts
apps/data_channel_registrar/wrangler.jsonc
apps/issued-jwt-registry/package.json
apps/organization_matchmaking/package.json
apps/user-credentials-cache/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

Enhanced Data Channel Registrar tests and fixed type issues across multiple services.
**New on `data_channel_registrar`**
- Added comprehensive test coverage, including tests for user roles (org admin, data custodian)
- Created test utilities with mock user data and helper functions
- Fixed type definitions in the Data Channel Registrar and AuthX Token API
- Removed unnecessary console.log statements
- Added error handling for non-existent data channels
- Updated package dependencies to use catalog version for `@vitest/istanbul` for consistency
- Added test coverage configuration on `data_channel_registrar`
- Removed unnecesary cleanup of Durable Object in teardown. Causes memory leaks, and it is not necesarry when `isolatedStorage: true` in `vitest.config.ts`
- …

test(coverage): data_registrar added CRUD validations for org-admin and data-custodian

---

apps/authx_authzed_api/.dev.vars.example
apps/authx_authzed_api/README.md
apps/authx_authzed_api/global-setup.ts
apps/authx_authzed_api/test/index.spec.ts
apps/authx_authzed_api/vitest.config.ts
apps/authx_token_api/global-setup.ts
apps/authx_token_api/vitest.config.ts
apps/data_channel_gateway/global-setup.ts
apps/data_channel_gateway/package.json
apps/data_channel_gateway/vitest.config.ts
apps/data_channel_registrar/global-setup.ts
apps/data_channel_registrar/vitest.config.ts
apps/organization_matchmaking/global-setup.ts
apps/organization_matchmaking/vitest.config.ts
run_local_dev.sh
start_authzed.sh

Updated AuthZed port from 8443 to 8449 across all services to avoid port conflicts.
- Changed the AuthZed HTTP port from 8443 to 8449 in all configuration files, documentation, and scripts
- Updated port references in:
- `.dev.vars.example` files
- README documentation
- Test configurations
- Global setup scripts for various services
- Vitest configuration files
- Local development scripts
- Added a new `start_authzed.sh` script to simplify starting the AuthZed container
- Updated the data channel gateway dev port to 4008
- Removed unused helper functions in test files
- Fixed some code formatting issues
1. Run the new `start_authzed.sh` script to start the AuthZed container
2. Verify that AuthZed is accessible on port 8449
3. Run tests for the affected services to ensure they connect …

chore(setup): create standalone authzed start script and removed rm flag

---

apps/authx_authzed_api/wrangler.jsonc
apps/authx_token_api/wrangler.jsonc
apps/catalyst-ui-worker/wrangler.jsonc
apps/data_channel_gateway/wrangler.jsonc
apps/data_channel_registrar/wrangler.jsonc
apps/issued-jwt-registry/wrangler.jsonc
apps/organization_matchmaking/wrangler.jsonc
apps/user-credentials-cache/wrangler.jsonc

Added UXR environment configuration and updated domain patterns across all Cloudflare Workers.
- Added a new `uxr` environment configuration across all worker configurations
- Commented out the `demo` environment configuration in all workers
- Updated domain patterns for preview, staging, and production environments
- Changed domain pattern from `preview.orbisops.io` to `preview.catalyst.devintelops.io`
- Added proper configuration for staging environment in catalyst-ui-worker
- Configured production environment services in catalyst-ui-worker
- Updated gateway domain patterns to include environment prefixes (e.g., `preview.gateway.catalyst.devintelops.io`)
- Fixed trailing commas in JSON configuration files for consistency
1. Deploy the workers to verify the new UXR environment is …

feat: add UXR environment and update deployment configs

---

apps/data_channel_gateway/src/index.ts
apps/data_channel_gateway/tests/validate-tokens.spec.ts

~~NOTE: this can not be merged until https://github.com/orbisoperations/catalyst-proxy-service/issues/22 is done.~~
can now merge this in, since we have:
---------------------
feat: add multi-pair validation for data channel access
moving changes to data channel gateway
feat: add bulk token validation endpoint and tests
```
ihammerstrom@Ians-MacBook-Pro catalyst % cd /Users/ihammerstrom/Desktop/code/catalyst_and_related/catalyst/apps/data_channel_gateway && npm test tests/validate-tokens.spec.ts       cd /Users/ihammerstrom/Desktop/code/catalyst_and_related/catalyst/apps/data_channel_gateway && npm test tests/validate-tokens.spec.ts
> test
> vitest tests/validate-tokens.spec.ts
2025-05-29 10:46:27.329 INFO    /node_modules/.vite-temp/vitest.config.ts.timestamp-1748515587325-187b57ab61055.m …
```

feat: add multi-pair validation for data channel access

---

apps/catalyst-ui-worker/tests/issued_jwt_registry.spec.ts
apps/data_channel_gateway/src/index.ts
apps/issued-jwt-registry/src/index.ts
apps/issued-jwt-registry/tests/issued_jwt_registry.spec.ts

The "delete" button for API keys in the UI actually makes the keys invalid for accessing associated data channels, as well as makes them no longer show up in the UI.
- Modified the `list` method in `I_JWT_Registry_DO` to filter out items with `deleted` status
- Updated `isOnRevocationList` to consider deleted items as revoked
- Added new test cases to verify deleted items are properly handled:
- Deleted items are excluded from list results
- Deleted items are considered to be on the revocation list
- Improved code formatting and style consistency across files
- Removed unused imports and variables
1) Delete an API key in the UI.
2) Verify it no longer shows up in API key UI view (it did before)
3) Verify it's no longer usable to receive data from a data channel (it was still usable …

fix: ensure deleted API keys are properly invalidated and filtered from UI

---

.github/workflows/dependency_management.yaml
.github/workflows/deployment_to_demo.yaml
.github/workflows/deployment_to_staging.yaml

Upgraded Node.js version from 18 to 20 in GitHub workflow files.
Updated the Node.js version from 18 to 20 in three GitHub workflow files:
- `.github/workflows/dependency_management.yaml`
- `.github/workflows/deployment_to_demo.yaml`
- `.github/workflows/deployment_to_staging.yaml`
This ensures all CI/CD pipelines use Node.js 20 consistently.
1. Verify that the GitHub workflows run successfully with the new Node.js version
2. Check that all build, test, and deployment processes complete without errors
3. Confirm that the application functions correctly in demo and staging environments
Node.js 18 is approaching end-of-life (April 2025), while Node.js 20 is the current LTS version with longer support. Upgrading ensures we're using a more modern runtime with better performance, security …

fix(workflows): updated github workflows to use Node 20

---

apps/catalyst-ui-worker/package.json

Updated the preview command to use port 4000 for the catalyst-ui-worker application.
Modified the `preview` script in the `package.json` file to specify port 4000 when running the preview command. The command now includes the additional parameter `-- --port=4000`.
1. Run `npm run preview` or `yarn preview` in the catalyst-ui-worker directory
2. Verify that the application is accessible on port 4000 (http://localhost:4000)
3. Confirm that the preview functionality works as expected on the specified port
This change ensures the preview server runs on a consistent port (4000), which helps prevent port conflicts with other services and provides developers with a predictable URL for local testing. This is especially useful in development environments where multiple services might be running …

fix: add port to preview local opennext js

---

apps/catalyst-ui-worker/app/actions/channels.ts
apps/catalyst-ui-worker/app/actions/i-jwt-registry.ts
apps/catalyst-ui-worker/app/actions/tokens.ts
apps/catalyst-ui-worker/components/channels/ChannelDetails.tsx
apps/catalyst-ui-worker/components/channels/CreateChannelForm.tsx
apps/catalyst-ui-worker/components/layouts/components/index.tsx
apps/catalyst-ui-worker/components/tokens/ListTokens.tsx

Fixed type safety issues with user organization data by explicitly converting organization values to strings.
- Added explicit string type conversions for `user?.custom.org` values throughout the codebase
- Removed unused CloudflareEnv imports from server action files
- Added null coalescing operator for organization display in UI components
- Fixed a boolean conversion in the token listing component
1. Log in with different user accounts to verify organization information displays correctly
2. Create and edit data channels to ensure organization information is properly saved
3. Check token listings to confirm they display correctly for both admin and non-admin users
The application was experiencing type safety issues when handling organization data from user objects. The organization …

fix: add casting to new unknowns

---

apps/authx_token_api/package.json
apps/authx_token_api/src/index.ts
apps/authx_token_api/test/integration/index.spec.ts
apps/authx_token_api/test/unit/durable_object_security_module.spec.ts
apps/authx_token_api/test/unit/jwt.spec.ts
apps/authx_token_api/test/unit/keystate.spec.ts
apps/authx_token_api/test/unit/signSystemJWT.spec.ts
apps/authx_token_api/vitest.integration.config.ts
apps/authx_token_api/vitest.unit.config.ts

Added system service JWT signing capability to the AuthX Token API and improved test organization.
- Added `signSystemJWT` method to enable service-to-service authentication without requiring user tokens
- Implemented security controls including service allowlisting and duration limits
- Reorganized test files into unit and integration directories
- Added separate Vitest configurations for unit and integration tests
- Added npm scripts for running unit and integration tests separately
1. Run unit tests with `npm run test:unit`
2. Run integration tests with `npm run test:integration`
3. Test the new system JWT functionality by calling the `signSystemJWT` method with:
```js
const request = {
callingService: "data-channel-certifier",
channelId: "test-channel-id",
purpose: …
```

feat(data-channel-certifier): create signSystemJWT in authx token api for later use

---

apps/catalyst-ui-worker/app/actions/validation.ts
apps/catalyst-ui-worker/components/channels/ListChannels.tsx
apps/catalyst-ui-worker/components/channels/ValidationStatus.tsx
apps/catalyst-ui-worker/env.d.ts
apps/catalyst-ui-worker/wrangler.jsonc

Added data channel validation functionality to the UI, allowing users to verify if their data channels are properly configured.
- Created a new server action `validateChannel` that communicates with the data-channel-certifier service
- Added a validation button to the data channels list that allows users to check channel validity
- Implemented a validation status badge that displays the result (valid, invalid, or error)
- Added tooltips to show validation error details when hovering over invalid status badges
- Updated the data channel table to include a validation column
- Added the DATA_CHANNEL_CERTIFIER service binding to all environments in wrangler.jsonc
1. Navigate to the data channels list in the UI
2. For any data channel, click the "Validate" button
3. Observe the validation …

feat(data-channel-certifier): add basic data channel val ui integration

---

apps/data-channel-certifier/src/env.d.ts
apps/data-channel-certifier/src/worker.ts
apps/data-channel-certifier/test/unit/scheduled-validation.spec.ts
apps/data_channel_registrar/package.json
apps/data_channel_registrar/src/worker.ts
apps/data_channel_registrar/test/integration/catalyst-token.spec.ts
apps/data_channel_registrar/test/integration/index.spec.ts
apps/data_channel_registrar/test/integration/listAll.spec.ts
apps/data_channel_registrar/test/integration/user-roles.spec.ts
apps/data_channel_registrar/test/unit/listAll.spec.ts
apps/data_channel_registrar/vitest.integration.config.ts
apps/data_channel_registrar/vitest.unit.config.ts

Updated the Data Channel Certifier to only validate enabled channels and added comprehensive unit tests for the new functionality.
- Modified `DATA_CHANNEL_REGISTRAR.list()` to `listAll()` with parameters for namespace and filtering by access switch
- Updated the Data Channel Certifier to only validate channels with `accessSwitch: true`
- Added unit tests for scheduled validation in the Data Channel Certifier
- Added both unit and integration tests for the new `listAll()` method in the Data Channel Registrar
- Restructured the Data Channel Registrar tests into separate unit and integration directories
- Added separate test configuration files for unit and integration tests
1. Run the unit tests for the Data Channel Certifier:
```
cd apps/data-channel-certifier
pnpm test
```
2. Run the …

feat(data-channel-certifier): add listAll for sys service reorg tests add schedueld validation

---

.gitignore
apps/authx_token_api/src/env.d.ts
apps/authx_token_api/wrangler.jsonc
apps/catalyst-ui-worker/README.md
apps/catalyst-ui-worker/cloudflare-env.d.ts
apps/catalyst-ui-worker/tests/env.d.ts
apps/catalyst-ui-worker/tests/issued_jwt_registry.spec.ts
apps/catalyst-ui-worker/wrangler.jsonc
apps/catalyst_cli/tsconfig.tsbuildinfo
apps/issued-jwt-registry/tests/env.d.ts
packages/schemas/src/core/env.ts
packages/schemas/src/core/services.ts

Renamed `ISSUED_JWT_WORKER` to `ISSUED_JWT_REGISTRY` across the codebase for consistency.
- Updated service binding name from `ISSUED_JWT_WORKER` to `ISSUED_JWT_REGISTRY` in multiple applications:
- catalyst-ui-worker
- authx_token_api
- packages/schemas
- Added missing service bindings for `ISSUED_JWT_REGISTRY` in authx_token_api wrangler.jsonc for all environments
- Updated references in type definitions, tests, and documentation
- Added *.tsbuildinfo to .gitignore and removed an existing tsbuildinfo file
1. Verify that all services start correctly with the updated binding names
2. Run tests for the affected applications to ensure they pass with the new binding names
3. Test JWT-related functionality in the UI to confirm the service connections work properly
This change standardizes the …

feat: all apps use consistent ISSUED_JWT_REGISTRY binding name
